### ISSUE TITLE
Increase iteration count

### ISSUE THREAD

**Issue by KevinAtSesam** [nremond/pbkdf2-scala#13]
Going through the implementation of the PBKDF2 algorithm, I found that this library defaults to HMAC + SHA512 with 20.000 iterations. This security setting was decided upon 6 years ago, and now it is getting outdated. 

Original commit: https://github.com/nremond/pbkdf2-scala/commit/093f901e341c951f8b0ab34bfff84d67920242d7

The adage that processing power doubles every two years, certainly shines a new light on the decision of 6 years ago. 20.000 is on the low end now, and it would be preferable to increase the default amount of hashes so that zero-config implementations are still reasonably secure.

Projects like OWASP recommend 120.000 iterations for HMAC + SHA512 and as such, I would recommend you to increase the default iteration count to 120.000

https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet.html#pbkdf2

_Minor details: The README says that you default to SHA256 which is obviously incorrect, and the IETF link explaining the iterations is dead._

**Comment by DemuirGos** [comment]
shouldn't this issue be closed ? since as far as I saw the iteration count has been updated to 120_000

**Comment by KevinAtSesam** [comment]
Not sure. The updated iteration count has not been released yet. The current MVN package is from 2019 so until there is an update to the package, the issue is still relevant.

@nremond Do you intend to release a 0.7.0 with the increased iteration count?

**Comment by KevinAtSesam** [comment]
@DemuirGos The package has updated and is being distributed with version number 0.7.0: 
- https://index.scala-lang.org/nremond/pbkdf2-scala/artifacts/pbkdf2-scala
- https://mvnrepository.com/artifact/io.github.nremond/pbkdf2-scala_3/0.7.0

@nremond Thanks man
