### ISSUE TITLE
Scala 3

### ISSUE THREAD

**Issue by 0xSilverest** [nremond/pbkdf2-scala#15]
Interested in using this package in one of my scala 3 projects, would be a nice to have.
I've forked repo and started working on a migration to scala 3, if that's not a problem.

**Comment by nremond** [comment]
Please, go ahead.

**Comment by Silverest12** [comment]
#16 got the upgrade here there's a problem it forced the update for testing libraries for scala 3, and had some changes on the library's core as for FlatSpec to AnyFlatSpec, which required the removal of scala 2.11.
